//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ocean.UI.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class IconsResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public IconsResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ocean.UI.Core.Resources.IconsResource", typeof(IconsResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M23.20001,23.466996L31.733001,23.466996 31.733001,31.999999 23.20001,31.999999z M11.600002,23.466996L20.134,23.466996 20.134,31.999999 11.600002,31.999999z M0,23.466996L8.5329992,23.466996 8.5329992,31.999999 0,31.999999z M23.20001,11.733L31.733001,11.733 31.733001,20.266999 23.20001,20.266999z M11.600002,11.733L20.134,11.733 20.134,20.266999 11.600002,20.266999z M0,11.733L8.5329992,11.733 8.5329992,20.266999 0,20.266999z M23.20001,0L31.733001,0 31.733001,8.5330002 23.20001,8.5330002z M11.600002,0L20.134,0  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string WindowsMany {
            get {
                return ResourceManager.GetString("WindowsMany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M20,17.999023L29.998993,17.999023C31.098999,17.999023,32,18.901001,32,20L32,30C32,31.100037,31.098999,32,29.998993,32L20,32C18.899994,32,17.998993,31.100037,17.998993,30L17.998993,20C17.998993,18.901001,18.899994,17.999023,20,17.999023z M2,17.999023L11.998993,17.999023C13.098999,17.999023,14,18.901001,14,20L14,30C14,31.100037,13.098999,32,11.998993,32L2,32C0.8999939,32,0,31.100037,0,30L0,20C0,18.901001,0.8999939,17.999023,2,17.999023z M20,0L29.998993,0C31.098999,0,32,0.90100098,32,2L32,12C32,13.100037,31.09 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string WindowsRounded {
            get {
                return ResourceManager.GetString("WindowsRounded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M19.294006,17.646957L32,17.646957 32,30.353 19.294006,30.353z M0,17.646957L12.707001,17.646957 12.707001,30.353 0,30.353z M19.294006,0L32,0 32,12.705982 19.294006,12.705982z M0,0L12.707001,0 12.707001,12.705982 0,12.705982z.
        /// </summary>
        public static string WindowsSharp {
            get {
                return ResourceManager.GetString("WindowsSharp", resourceCulture);
            }
        }
    }
}
